//Queue names -- Producer
export const AUDIO_PROCESSING_QUEUE = 'audio-processing'
export const TRANSCRIPTION_QUEUE = 'transcription-processing'
export const DIARISATION_QUEUE = 'diarisation-processing'
export const MERGE_QUEUE = 'merge-processing'
export const LLM_QUEUE = 'llm-processing'
export const ACTION_QUEUE = 'action-processing'
export const EMAIL_QUEUE = 'email-processing'
//Queue names -- Consumer
export const PROCESS_AUDIO_JOB = 'process-audio-job'
export const PROCESS_TRANSCRIPTION_JOB = 'process-transcription-job'
export const PROCESS_DIARISATION_JOB = 'process-diarisation-job'
export const PROCESS_MERGE_JOB = 'process-merge-job'
export const PROCESS_LLM_JOB = 'process-llm-job'
export const PROCESS_ACTION_JOB = 'process-action-job'
export const PROCESS_EMAIL_JOB = 'process-email-job'